# Pregunta 6. Consulta que cree al menos una columna calculada.

1. Es decir, que la consulta cree un nuevo campo dependiendo de otro campo, o calculado a partir de otras columnas.

2. Ejemplo: a) campo Apto/NoApto dependiendo de las notas de alumnos b) cálculo imc a partir del peso y la altura.

3. Resultado final, Jupyter Notebook o proyecto Python con el código.

### IMPORT
---

In [1]:
import numpy as np
import pandas as pd

### Calculated column
---

- La columna calculada es "no_hospitalization_required".
- Calculo: el número de personas enfermas menos el número de personas hospitalisadas.  
Lo que quiere decir que esas personas enfermaron levemente y no necesitaron ser hospitalizadas.

In [2]:
data: pd.DataFrame = pd.read_csv("../data/cleaned_csv/3-question_results/cases.csv", index_col="case_id")
data["no_hospitalization_required"] = data['illnesses'] - data['hospitalizations']
data

,year,month,state,location,species,status,illnesses,hospitalizations,fatalities,no_hospitalization_required
case_id,,,,,,,,,,
1,1998,January,California,Restaurant,NaN,NaN,20,0.0,0.0,20.0
2,1998,January,California,NaN,NaN,NaN,112,0.0,0.0,112.0
3,1998,January,California,Restaurant,NaN,NaN,35,0.0,0.0,35.0
4,1998,January,California,Restaurant,Scombroid toxin,Confirmed,4,0.0,0.0,4.0
5,1998,January,California,Private Home/Residence,Salmonella enterica,Confirmed,26,3.0,0.0,23.0
...,...,...,...,...,...,...,...,...,...,...
17391,2015,December,Wisconsin,Restaurant,Norovirus genogroup II,Confirmed,4,0.0,0.0,4.0
17392,2015,December,Wisconsin,Private Home/Residence,Norovirus genogroup II,Confirmed,16,0.0,0.0,16.0
17393,2015,December,Wisconsin,Nursing Home/Assisted Living Facility,Norovirus genogroup II,Confirmed,43,3.0,0.0,40.0
17394,2015,December,Wisconsin,Fast Food Restaurant,Norovirus genogroup II,Confirmed,5,0.0,0.0,5.0
17395,2015,December,Wyoming,NaN,NaN,NaN,3,0.0,0.0,3.0